import type { ActorId, Flow, Mission } from './types'

export const actors: Record<ActorId, { label: string; symbol: string; decisions: string; accounts: string; blindSpot: string }> = {
  household: { label: 'Haushalte', symbol: '⌂', decisions: 'Konsum, Sparen, Arbeitsangebot', accounts: 'Yd, C, S, T, TR', blindSpot: 'Individuelles Sparen ist nicht automatisch gesamtwirtschaftliche Nachfrage.' },
  firm: { label: 'Unternehmen', symbol: '⌘', decisions: 'Produktion, Investition, Preise, Beschäftigung', accounts: 'Umsatz, Löhne, I, Lager', blindSpot: 'Umsatz und Gewinn sind nicht identisch.' },
  state: { label: 'Staat', symbol: '⚑', decisions: 'Steuern, Transfers, Ausgaben', accounts: 'T, TR, G, Budgetsaldo', blindSpot: 'Defizit ist ein Strom; Staatsschulden sind ein Bestand.' },
  finance: { label: 'Finanzsektor', symbol: '▦', decisions: 'Kreditbedingungen und Weitergabe des Zinses', accounts: 'Kredite, Einlagen, Zins', blindSpot: 'Günstiger Kredit garantiert keine Investition.' },
  foreign: { label: 'Ausland', symbol: '◎', decisions: 'Export- und Importnachfrage', accounts: 'X, M', blindSpot: 'Importe sind eine Entnahme, aber nicht grundsätzlich negativ.' },
}

export const flows: Flow[] = [
  { id: 'labor', from: 'household', to: 'firm', label: 'Faktorleistungen', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'income' },
  { id: 'income', from: 'firm', to: 'household', label: 'Faktoreinkommen', kind: 'money', amount: 620, period: 'je Quartal', counterpart: 'labor' },
  { id: 'goods', from: 'firm', to: 'household', label: 'Konsumgüter und Dienste', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'consumption' },
  { id: 'consumption', from: 'household', to: 'firm', label: 'Konsumausgaben C', kind: 'money', amount: 500, period: 'je Quartal', counterpart: 'goods' },
  { id: 'tax', from: 'household', to: 'state', label: 'Steuern T', kind: 'tax-transfer', amount: 120, period: 'je Quartal', counterpart: 'publicServices' },
  { id: 'publicServices', from: 'state', to: 'household', label: 'Öffentliche Leistungen', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'tax' },
  { id: 'transfer', from: 'state', to: 'household', label: 'Transfers TR', kind: 'tax-transfer', amount: 32, period: 'je Quartal', counterpart: 'tax' },
  { id: 'saving', from: 'household', to: 'finance', label: 'Sparen S', kind: 'credit-interest', amount: 122, period: 'je Quartal', counterpart: 'credit' },
  { id: 'credit', from: 'finance', to: 'firm', label: 'Kredite für Investitionen', kind: 'credit-interest', amount: 110, period: 'je Quartal', counterpart: 'interest' },
  { id: 'interest', from: 'firm', to: 'finance', label: 'Zins und Tilgung', kind: 'money', amount: null, period: 'je Quartal', counterpart: 'credit' },
  { id: 'export', from: 'firm', to: 'foreign', label: 'Exporte X', kind: 'import-export', amount: 75, period: 'je Quartal', counterpart: 'exportPayment' },
  { id: 'exportPayment', from: 'foreign', to: 'firm', label: 'Exporterlöse', kind: 'money', amount: 75, period: 'je Quartal', counterpart: 'export' },
  { id: 'import', from: 'foreign', to: 'household', label: 'Importgüter M', kind: 'import-export', amount: 105, period: 'je Quartal', counterpart: 'importPayment' },
  { id: 'importPayment', from: 'household', to: 'foreign', label: 'Importzahlungen', kind: 'money', amount: 105, period: 'je Quartal', counterpart: 'import' },
]

const basicFlowTask = {
  cards: [
    { id: 'card-goods', label: 'Konsumgüter', target: 'firm-household' },
    { id: 'card-c', label: 'Konsumausgaben', target: 'household-firm' },
    { id: 'card-labor', label: 'Arbeitsleistung', target: 'household-firm' },
    { id: 'card-wage', label: 'Lohnzahlung', target: 'firm-household' },
  ],
  zones: [
    { id: 'household-firm', label: 'Haushalte → Unternehmen' },
    { id: 'firm-household', label: 'Unternehmen → Haushalte' },
  ],
}

export const missions: Mission[] = [
  {
    id: 'sparen-investieren',
    title: 'Sparen oder investieren?',
    level: 'FOS 11',
    duration: '3 Runden · ca. 20 Minuten',
    summary: 'Untersuche, warum individuelles Sparen und gesamtwirtschaftliches Gleichgewicht nicht dasselbe sind.',
    actors: ['household', 'firm'],
    initialAccounts: { C: 500, I: 80, G: 0, X: 0, M: 0, T: 0, TR: 0, S: 80 },
    initialIndicators: { growth: 1.4, inflation: 2.0, employment: 94.0, interestRate: 3.5, publicDebt: 0 },
    rounds: [
      {
        title: 'Ströme und Gegenbuchungen',
        situation: 'Haushalte stellen Faktorleistungen bereit und verwenden ihr Einkommen für Konsum und Sparen.',
        learningGoal: 'Reale und monetäre Gegenströme sicher zuordnen.',
        event: 'Vier Transaktionskarten warten auf ihre Stromrichtung.',
        instruction: 'Ordne zuerst die Karten zu. Entscheide dann, wie die Haushalte ihr Einkommen verwenden.',
        tip: 'Frage bei jeder Transaktion: Wer leistet – und wer zahlt?',
        checkAfter: 'Prüfe Richtung, Stromart und die Gegenbuchung.',
        flowTask: basicFlowTask,
        choices: [
          { id: 'consume', label: 'Konsum stabil halten', description: 'C und S bleiben vorerst unverändert.', effect: {}, direct: 'Die geplante Konsumnachfrage bleibt stabil.', delayed: 'Produktion und Beschäftigung erhalten daraus zunächst keinen zusätzlichen Impuls.', distribution: 'Der Konsumspielraum der Haushalte bleibt gleich.', conflict: 'Keine zusätzliche Vorsorge, aber stabile Nachfrage.', assumptions: ['Unternehmen halten ihre Investitionspläne ein.'] },
          { id: 'save', label: '15 Mrd. € mehr sparen', description: 'C sinkt, S steigt bei unverändertem I.', effect: { C: -15, S: 15 }, direct: 'Die Konsumnachfrage sinkt um 15 Mrd. €.', delayed: 'Bei unverändertem I entstehen zunächst Lagerbestände; Produktion kann in der Folgerunde sinken.', distribution: 'Sparfähige Haushalte bauen Vermögen auf; einkommensschwächere Haushalte können weniger reagieren.', conflict: 'Individuelle Vorsorge steht kurzfristig einer schwächeren Gesamtnachfrage gegenüber.', assumptions: ['Investitionen bleiben zunächst konstant.', 'Preise reagieren kurzfristig nicht vollständig.'] },
        ],
      },
      {
        title: 'S und I ausbalancieren',
        situation: 'Nach höherem Sparen liegen Entnahmen über den geplanten Zuführungen.',
        learningGoal: 'Plan-Saldo und ungeplante Lagerveränderung berechnen.',
        event: 'Die Unternehmen entscheiden, ob sie ihre Investition anpassen.',
        instruction: 'Lies Entnahmen und Zuführungen. Wähle eine Investitionsreaktion und begründe die Prognose.',
        tip: 'Plan-Saldo = Zuführungen − Entnahmen. Ein negativer Saldo bedeutet zunächst Lageraufbau.',
        checkAfter: 'Unterscheide Lagerwirkung in dieser Runde und Produktionswirkung in der Folgerunde.',
        choices: [
          { id: 'invest-up', label: 'Investitionen +15', description: 'Unternehmen nutzen Finanzierung für Maschinen.', effect: { I: 15 }, direct: 'I erhöht die geplanten Zuführungen.', delayed: 'Kapazität und Beschäftigung können steigen, wenn Absatz erwartet wird.', distribution: 'Beschäftigte in Investitionsgüterbranchen profitieren zuerst.', conflict: 'Höhere Kapazität birgt bei schwacher Nachfrage ein Auslastungsrisiko.', assumptions: ['Kreditzugang ist vorhanden.', 'Unternehmen erwarten ausreichenden Absatz.'] },
          { id: 'invest-flat', label: 'Investitionen unverändert', description: 'Unternehmen warten wegen unsicherer Nachfrage ab.', effect: {}, direct: 'Die Lücke zwischen S und I bleibt bestehen.', delayed: 'Lageraufbau kann Produktions- und Beschäftigungsanpassungen auslösen.', distribution: 'Beschäftigte tragen einen größeren Teil des Anpassungsrisikos.', conflict: 'Liquiditätssicherung versus Beschäftigungsstabilität.', assumptions: ['Keine andere Nachfragekomponente gleicht die Lücke aus.'] },
        ],
      },
      {
        title: 'Vom Lager zur Folgerunde',
        situation: 'Die Inventur macht den Ex-post-Ausgleich sichtbar. Er ist keine Stabilitätsgarantie.',
        learningGoal: 'Bestandsänderung und verzögerte Anpassung erklären.',
        event: 'Unternehmen planen die nächste Produktionsperiode.',
        instruction: 'Wähle eine Reaktion und formuliere eine begründete Wirkungskette.',
        tip: 'Lager ist Bestand; die ungeplante Lagerinvestition wird für eine Periode als Strom gemessen.',
        checkAfter: 'Prüfe Kontenlogik, Zeitbezug und Annahmen.',
        choices: [
          { id: 'adjust-gradual', label: 'Produktion schrittweise anpassen', description: 'Nur ein Teil der Absatzlücke wirkt sofort auf die Planung.', effect: {}, direct: 'Lagerbestände signalisieren eine Planabweichung.', delayed: 'Produktion, Einkommen und Beschäftigung reagieren mit Verzögerung.', distribution: 'Kurzarbeit oder weniger Neueinstellungen treffen Erwerbseinkommen.', conflict: 'Lagerkosten versus vorschneller Kapazitätsabbau.', assumptions: ['Unternehmen interpretieren den Nachfragerückgang als teilweise anhaltend.'] },
          { id: 'price-first', label: 'Zuerst Preise und Absatz testen', description: 'Unternehmen bauen Lager über Angebote ab.', effect: { C: 5 }, direct: 'Preisaktionen können den Absatz stützen.', delayed: 'Die Produktionsanpassung fällt eventuell kleiner aus.', distribution: 'Konsumierende profitieren, Margen der Unternehmen sinken.', conflict: 'Beschäftigungssicherung versus Ertragslage.', assumptions: ['Haushalte reagieren auf niedrigere Preise.', 'Margen erlauben Preisnachlässe.'] },
        ],
      },
    ],
  },
  {
    id: 'staat-finanzsektor',
    title: 'Staat und Finanzsektor im Kreislauf',
    level: 'FOS 11/12',
    duration: '3 Runden · ca. 25 Minuten',
    summary: 'Verfolge Steuern, Transfers, Staatsausgaben, Sparen und Kredite samt Gegenbuchungen.',
    actors: ['household', 'firm', 'state', 'finance'],
    initialAccounts: { C: 470, I: 95, G: 115, X: 0, M: 0, T: 110, TR: 30, S: 120 },
    initialIndicators: { growth: 0.8, inflation: 2.2, employment: 92.5, interestRate: 4.0, publicDebt: 860 },
    rounds: [
      {
        title: 'Steuern, Transfers und öffentliche Nachfrage',
        situation: 'Der Staat erhebt Steuern, zahlt Transfers und kauft Güter und Dienstleistungen.',
        learningGoal: 'T, TR und G kontenlogisch unterscheiden.',
        event: 'Ein Konjunkturprogramm von 12 Mrd. € wird diskutiert.',
        instruction: 'Wähle die Zusammensetzung und prognostiziere direkte und verzögerte Folgen.',
        tip: 'TR verändert Yd; G ist selbst eine Komponente der Güternachfrage.',
        checkAfter: 'Prüfe, ob du Defizit als Strom und Schulden als Bestand getrennt hast.',
        choices: [
          { id: 'g-up', label: 'Öffentliche Investitionen +12', description: 'Der Staat bestellt Infrastruktur.', effect: { G: 12 }, direct: 'G und damit die geplanten Zuführungen steigen.', delayed: 'Produktion und Beschäftigung können nach Planung und Vergabe folgen.', distribution: 'Bau- und Zulieferbranchen profitieren zuerst.', conflict: 'Konjunkturimpuls versus Budgetdefizit und mögliche Importanteile.', assumptions: ['Kapazitätsreserven sind vorhanden.', 'Projekte sind umsetzungsreif.'] },
          { id: 'tr-up', label: 'Transfers +12', description: 'Verfügbares Einkommen ausgewählter Haushalte steigt.', effect: { TR: 12, C: 8, S: 4 }, direct: 'Yd steigt; Verwendung auf C und S hängt von der Konsumneigung ab.', delayed: 'Nachfrage wirkt nur insoweit, wie Transfers konsumiert werden.', distribution: 'Niedrige Einkommen werden gezielt entlastet.', conflict: 'Zielgenauigkeit versus dauerhafte Budgetbelastung.', assumptions: ['Zwei Drittel der Transfers werden kurzfristig konsumiert.'] },
        ],
      },
      {
        title: 'Vom Sparen zum Kredit',
        situation: 'Banken vermitteln Einlagen und Kredite, prüfen aber Bonität und Erwartungen.',
        learningGoal: 'Kreditkanal als bedingte Wirkungskette erklären.',
        event: 'Der Marktzins fällt um einen Prozentpunkt.',
        instruction: 'Entscheide, wie stark I reagiert, und nenne die nötigen Annahmen.',
        tip: 'i ↓ bedeutet nicht automatisch I ↑.',
        checkAfter: 'Prüfe Kreditweitergabe, Kreditwürdigkeit und Absatzerwartungen.',
        choices: [
          { id: 'credit-strong', label: 'Starker Kreditimpuls', description: 'I steigt um 14 Mrd. €.', effect: { I: 14, interestRate: -1 }, direct: 'Finanzierungskosten sinken und Kreditanfragen nehmen zu.', delayed: 'Investition und später Kapazität können steigen.', distribution: 'Kreditwürdige Unternehmen profitieren stärker.', conflict: 'Wachstum versus Verschuldungs- und Preisrisiken.', assumptions: ['Banken geben den Zins weiter.', 'Bonität und Nachfrageerwartungen sind ausreichend.'] },
          { id: 'credit-weak', label: 'Schwache Weitergabe', description: 'I steigt nur um 4 Mrd. €.', effect: { I: 4, interestRate: -1 }, direct: 'Der Referenzzins sinkt, Kreditkonditionen folgen nur teilweise.', delayed: 'Die Investitionswirkung bleibt begrenzt.', distribution: 'Kleine Unternehmen profitieren bei strenger Bonitätsprüfung kaum.', conflict: 'Finanzstabilität versus breiter Kreditzugang.', assumptions: ['Risikoprämien bleiben hoch.', 'Absatzerwartungen sind verhalten.'] },
        ],
      },
      {
        title: 'Budgetsaldo und Schuldenstand',
        situation: 'Das Defizit dieser Runde verändert den Schuldenbestand, ist aber nicht mit ihm identisch.',
        learningGoal: 'Strom- und Bestandsgrößen korrekt interpretieren.',
        event: 'Die Finanzierung des Programms wird ausgewertet.',
        instruction: 'Wähle einen Konsolidierungspfad und begründe den Zeitbezug.',
        tip: 'Ein Defizit wird je Zeitraum gemessen; Schulden werden zu einem Zeitpunkt gemessen.',
        checkAfter: 'Prüfe Nebenwirkungen auf Nachfrage und Verteilung.',
        choices: [
          { id: 'gradual-budget', label: 'Schrittweise konsolidieren', description: 'T steigt in der nächsten Planung moderat.', effect: { T: 5, C: -3, S: -2 }, direct: 'Das verfügbare Einkommen sinkt leicht.', delayed: 'Der Budgetsaldo verbessert sich, die Nachfrage wird etwas gedämpft.', distribution: 'Die Wirkung hängt von der konkreten Steuerbasis ab.', conflict: 'Tragfähigkeit versus kurzfristige Stabilisierung.', assumptions: ['Steueraufkommen steigt wie geplant.', 'Keine starke Ausweichreaktion.'] },
          { id: 'protect-demand', label: 'Nachfrage zunächst schützen', description: 'Keine unmittelbare Konsolidierung.', effect: {}, direct: 'Der aktuelle Impuls bleibt bestehen.', delayed: 'Der Schuldenbestand kann durch weitere Defizite steigen.', distribution: 'Beschäftigungsrisiken werden kurzfristig begrenzt.', conflict: 'Aktuelle Beschäftigung versus künftiger Finanzierungsspielraum.', assumptions: ['Finanzierung bleibt zu tragbaren Zinsen möglich.'] },
        ],
      },
    ],
  },
  {
    id: 'export-kredit',
    title: 'Exportdämpfer und Kreditimpuls',
    level: 'FOS 13',
    duration: '4 Runden · ca. 30 Minuten',
    summary: 'Reagiere auf einen Exportausfall und bewerte den bedingten Kreditkanal.',
    actors: ['household', 'firm', 'state', 'finance', 'foreign'],
    initialAccounts: { C: 500, I: 110, G: 130, X: 75, M: 105, T: 120, TR: 32, S: 125 },
    initialIndicators: { growth: -1.8, inflation: 2.8, employment: 93.6, interestRate: 3.5, publicDebt: 1040 },
    rounds: [
      {
        title: 'Exportauftrag storniert',
        situation: 'Die Auslandsnachfrage sinkt um 12 %. Ein Auftrag über 10 Mrd. € entfällt.',
        learningGoal: 'X als Zuführung und den direkten Lagerkanal erklären.',
        event: 'X −10 Mrd. €; im selben Quartal gibt es keine Gegenmaßnahme.',
        instruction: 'Beobachte die Bilanz und entscheide, wie Unternehmen zunächst reagieren.',
        tip: 'Ein Nachfrageausfall ändert nicht augenblicklich die geplante Produktion.',
        checkAfter: 'Prüfe zuerst die Lageränderung, erst danach Produktion und Beschäftigung.',
        choices: [
          { id: 'wait', label: 'Eine Runde beobachten', description: 'Produktion bleibt im laufenden Quartal geplant.', effect: { X: -10 }, direct: 'Exporterlöse und Nachfrage sinken; Lager exportierender Unternehmen steigen.', delayed: 'Bei anhaltend niedrigen Aufträgen sinken Produktion und Beschäftigung.', distribution: 'Exportorientierte Regionen und Branchen sind stärker betroffen.', conflict: 'Abwarten vermeidet Überreaktion, erhöht aber Lagerkosten.', assumptions: ['Kapazitätsreserven vorhanden.', 'Keine Gegenmaßnahme im selben Quartal.'] },
          { id: 'cut-fast', label: 'Produktion sofort kürzen', description: 'C als Einkommensfolge sinkt frühzeitig.', effect: { X: -10, C: -6 }, direct: 'Produktion und Arbeitsstunden werden rasch gekürzt.', delayed: 'Niedrigere Einkommen können den Konsum zusätzlich dämpfen.', distribution: 'Beschäftigte in Exportbranchen tragen die frühe Anpassung.', conflict: 'Lagerkosten versus Beschäftigung und Einkommen.', assumptions: ['Der Exportrückgang wird als dauerhaft eingeschätzt.'] },
        ],
      },
      {
        title: 'Kreditimpuls setzen',
        situation: 'Die Zentralbank signalisiert günstigere Finanzierung. Investitionen reagieren nur bedingt.',
        learningGoal: 'Geldpolitik mit Annahmen statt Automatismus beurteilen.',
        event: 'Der Leitzins sinkt; Kreditweitergabe und Erwartungen sind offen.',
        instruction: 'Wähle ein realistisches Investitionsszenario und dokumentiere die Annahmen.',
        tip: 'Prüfe Zinsweitergabe, Bonität, Erwartungen und Kapazitätsauslastung.',
        checkAfter: 'Trenne direkten Finanzierungseffekt und verzögerte Realwirkung.',
        choices: [
          { id: 'i-medium', label: 'I steigt moderat um 8', description: 'Nur solide Projekte werden vorgezogen.', effect: { I: 8, interestRate: -0.75 }, direct: 'Kreditkosten sinken für einen Teil der Unternehmen.', delayed: 'Investitionsnachfrage stützt Produktion; Kapazität folgt später.', distribution: 'Bonitätsstarke Unternehmen profitieren früher.', conflict: 'Stabilisierung versus Verschuldung und Inflation.', assumptions: ['Banken geben den Zins teilweise weiter.', 'Unternehmen erwarten eine Nachfrageerholung.'] },
          { id: 'i-none', label: 'I reagiert kaum', description: 'Unsicherheit dominiert den Zinseffekt.', effect: { I: 1, interestRate: -0.75 }, direct: 'Finanzierung wird günstiger, aber Projekte werden nicht ausgelöst.', delayed: 'Der Exportdämpfer bleibt weitgehend bestehen.', distribution: 'Haushalte mit Zinseinkommen und Kreditnehmende sind unterschiedlich betroffen.', conflict: 'Niedrige Zinsen ohne starken Realimpuls.', assumptions: ['Absatzerwartungen bleiben schwach.', 'Kreditwürdigkeit begrenzt die Nachfrage.'] },
        ],
      },
      {
        title: 'Fiskalische Ergänzung',
        situation: 'Die Kreditwirkung reicht allein möglicherweise nicht zur Stabilisierung.',
        learningGoal: 'Fiskal- und Geldpolitik samt Zielkonflikten vergleichen.',
        event: 'Der Staat kann öffentliche Investitionen vorziehen.',
        instruction: 'Steuere G und berücksichtige Budget, Importe und Umsetzungsverzögerung.',
        tip: 'Ein Teil zusätzlicher Nachfrage kann in M abfließen.',
        checkAfter: 'Prüfe Plan-Saldo, Importanteil und Budgetwirkung.',
        choices: [
          { id: 'g-targeted', label: 'G +10, M +2', description: 'Gezielte Infrastruktur mit Importanteil.', effect: { G: 10, M: 2 }, direct: 'Die inländische Nachfrage steigt netto um 8 Mrd. €.', delayed: 'Beschäftigung und Produktivität können nach Vergabe steigen.', distribution: 'Begünstigt zunächst ausführende Branchen und Regionen.', conflict: 'Budgetdefizit und Importleck versus Stabilisierung.', assumptions: ['Projekte sind umsetzungsreif.', 'Es bestehen Kapazitätsreserven.'] },
          { id: 'no-g', label: 'Keine Fiskalmaßnahme', description: 'Automatische Anpassung abwarten.', effect: {}, direct: 'Der Staat setzt keinen zusätzlichen Nachfrageimpuls.', delayed: 'Private Anpassungen bestimmen Produktion und Beschäftigung.', distribution: 'Exportbranchen tragen den Schock stärker.', conflict: 'Budgetschonung versus Konjunkturstabilisierung.', assumptions: ['Private Nachfrage erholt sich ohne Staatseingriff.'] },
        ],
      },
      {
        title: 'Zielkonflikte auswerten',
        situation: 'Export, Kredit und Fiskalpolitik wirken mit verschiedenen Verzögerungen.',
        learningGoal: 'Wirkung, Annahme, Verteilung und Zielkonflikt zusammenführen.',
        event: 'Die Schlussrunde verlangt eine robuste statt eindeutige Empfehlung.',
        instruction: 'Wähle die Schwerpunktsetzung und reflektiere Unsicherheit.',
        tip: 'Mehrere fachlich vertretbare Antworten sind möglich, wenn die Bedingungen benannt sind.',
        checkAfter: 'Prüfe alle sechs Feedbackdimensionen.',
        choices: [
          { id: 'balanced', label: 'Befristeter Mix', description: 'Gezielte Fiskalstütze, vorsichtiger Kreditimpuls, Evaluation.', effect: { G: 4, I: 3, M: 1 }, direct: 'Zuführungen steigen stärker als Entnahmen.', delayed: 'Stabilisierung bleibt von Weitergabe und Erwartungen abhängig.', distribution: 'Gezielte Ausgestaltung kann Belastungen begrenzen.', conflict: 'Beschäftigung, Inflation und Budget müssen gemeinsam beobachtet werden.', assumptions: ['Maßnahmen sind befristet.', 'Inflationserwartungen bleiben verankert.'] },
          { id: 'stability', label: 'Preis- und Budgetstabilität', description: 'Keine weitere Nachfrageausweitung.', effect: {}, direct: 'Inflations- und Budgetrisiken werden nicht zusätzlich erhöht.', delayed: 'Erholung von Beschäftigung kann langsamer verlaufen.', distribution: 'Arbeitslose und exportabhängige Regionen tragen höhere Anpassungskosten.', conflict: 'Stabilität versus Beschäftigung.', assumptions: ['Der Schock ist vorübergehend.'] },
        ],
      },
    ],
  },
  {
    id: 'oelpreisschock',
    title: 'Ölpreisschock und Zielkonflikte',
    level: 'FOS 13',
    duration: '4 Runden · ca. 30 Minuten',
    summary: 'Unterscheide Kosten- und Nachfragekanal und steuere einen schwierigen Policy-Mix.',
    actors: ['household', 'firm', 'state', 'finance', 'foreign'],
    initialAccounts: { C: 505, I: 105, G: 125, X: 85, M: 100, T: 122, TR: 28, S: 116 },
    initialIndicators: { growth: 0.6, inflation: 3.1, employment: 94.2, interestRate: 3.75, publicDebt: 1025 },
    rounds: [
      {
        title: 'Importierter Kostenschock',
        situation: 'Energieimporte verteuern sich. Die Importrechnung steigt, Unternehmen melden höhere Kosten.',
        learningGoal: 'Angebots-/Kostenkanal und Nachfragekanal trennen.',
        event: 'M steigt um 14 Mrd. €; Inflation nimmt zunächst über Kosten zu.',
        instruction: 'Wähle eine erste Reaktion und erkläre den direkten Kanal.',
        tip: 'Höhere Inflation entsteht hier nicht zuerst aus überschießender Nachfrage.',
        checkAfter: 'Prüfe Importentnahme, Realeinkommen und Kostenüberwälzung.',
        choices: [
          { id: 'target-transfer', label: 'Gezielte Transfers', description: 'TR +10; davon C +7, S +3.', effect: { M: 14, TR: 10, C: 7, S: 3 }, direct: 'Betroffene Haushalte erhalten Einkommen, der Kostenschock bleibt aber bestehen.', delayed: 'Konsum stabilisiert sich; Nachfrage kann Preisauftrieb etwas verstärken.', distribution: 'Niedrige Einkommen werden relativ stärker entlastet.', conflict: 'Sozialer Ausgleich versus Budget und Nachfrageinflation.', assumptions: ['Transfers sind zielgenau.', '70 % werden kurzfristig konsumiert.'] },
          { id: 'wait-oil', label: 'Zunächst nicht intervenieren', description: 'Nur der Importpreisschock wird verbucht.', effect: { M: 14, C: -5 }, direct: 'Reale Kaufkraft und Konsum sinken.', delayed: 'Schwächere Nachfrage kann Beschäftigung belasten.', distribution: 'Energieintensive Haushalte und Unternehmen sind stärker betroffen.', conflict: 'Inflationsbegrenzung versus Realeinkommen und Beschäftigung.', assumptions: ['Der Ölpreisanstieg ist vorübergehend.'] },
        ],
      },
      {
        title: 'Geldpolitische Reaktion',
        situation: 'Inflation liegt über Ziel, zugleich schwächt sich die reale Aktivität ab.',
        learningGoal: 'Den Zielkonflikt der Geldpolitik beim Angebotsschock erklären.',
        event: 'Die Zinsentscheidung beeinflusst Nachfrage und Erwartungen mit Verzögerung.',
        instruction: 'Stelle die Reaktion ein und begründe den Zeithorizont.',
        tip: 'Der Leitzins senkt den Ölpreis nicht direkt.',
        checkAfter: 'Prüfe Erwartungen, Kreditkanal und Beschäftigungswirkung.',
        choices: [
          { id: 'rate-up', label: 'Zins +0,5 Punkte', description: 'Nachfrage und Inflationserwartungen sollen gedämpft werden.', effect: { I: -7, interestRate: 0.5 }, direct: 'Finanzierungskosten steigen.', delayed: 'I und Nachfrage sinken; Kosteninflation wird nur indirekt beeinflusst.', distribution: 'Kreditnehmende werden belastet, Sparerträge können steigen.', conflict: 'Preisstabilität versus Wachstum und Beschäftigung.', assumptions: ['Zinsänderung wird weitergegeben.', 'Erwartungen reagieren.'] },
          { id: 'rate-hold', label: 'Zins halten', description: 'Zweitrundeneffekte zunächst beobachten.', effect: {}, direct: 'Keine zusätzliche Veränderung der Finanzierungskosten.', delayed: 'Bei anhaltender Inflation können Erwartungen steigen.', distribution: 'Keine neue unmittelbare Kreditbelastung.', conflict: 'Konjunkturschutz versus Glaubwürdigkeit des Inflationsziels.', assumptions: ['Lohn-Preis-Zweitrundeneffekte bleiben begrenzt.'] },
        ],
      },
      {
        title: 'Fiskalische Feinsteuerung',
        situation: 'Breite Nachfrageprogramme könnten den Preisauftrieb erhöhen; gezielte Hilfen haben andere Verteilungswirkungen.',
        learningGoal: 'Instrumente nach Zielgenauigkeit und Nebenwirkungen beurteilen.',
        event: 'Es stehen 12 Mrd. € fiskalischer Spielraum zur Diskussion.',
        instruction: 'Wähle ein Instrument und prognostiziere Verteilung und Zielkonflikt.',
        tip: 'Entlastung, Nachfrageimpuls und Angebotswirkung sind nicht identisch.',
        checkAfter: 'Prüfe zeitliche Befristung und Begünstigte.',
        choices: [
          { id: 'efficiency', label: 'Effizienzinvestitionen', description: 'G +12, M +3 für Energieanlagen.', effect: { G: 12, M: 3 }, direct: 'Nachfrage und Importbedarf steigen zunächst.', delayed: 'Energieeffizienz kann Kosten und Importabhängigkeit senken.', distribution: 'Gebäudeeigentümer und beteiligte Branchen profitieren zuerst.', conflict: 'Kurzfristiger Preisdruck versus langfristige Angebotswirkung.', assumptions: ['Projekte werden umgesetzt.', 'Effizienzgewinne treten ein.'] },
          { id: 'broad-tax', label: 'Breite Steuersenkung', description: 'T −12; C +7 und S +5.', effect: { T: -12, C: 7, S: 5 }, direct: 'Yd steigt, Verwendung verteilt sich auf C und S.', delayed: 'Nachfrage steigt breit, aber wenig zielgenau.', distribution: 'Absolute Entlastung kann bei höheren Einkommen größer sein.', conflict: 'Kaufkraft versus Inflation und Budget.', assumptions: ['Haushalte konsumieren knapp 60 % der Entlastung.'] },
        ],
      },
      {
        title: 'Robuste Schlussstrategie',
        situation: 'Inflation, Beschäftigung und Verteilung reagieren unterschiedlich schnell.',
        learningGoal: 'Eine bedingte Politikempfehlung formulieren.',
        event: 'Neue Daten sind unsicher; die Mission endet nach dieser Entscheidung.',
        instruction: 'Wähle eine Strategie und reflektiere, welche Daten deine Entscheidung ändern würden.',
        tip: 'Eine robuste Empfehlung nennt Bedingungen und Revisionspunkte.',
        checkAfter: 'Prüfe Kostenkanal, Nachfragekanal, Verteilung und Zeitbezug.',
        choices: [
          { id: 'targeted-mix', label: 'Gezielt entlasten und investieren', description: 'Befristete Transfers plus Angebotsinvestition.', effect: { TR: 5, G: 6, C: 3, M: 1 }, direct: 'Kaufkraft und Nachfrage werden begrenzt gestützt.', delayed: 'Investitionen können die Angebotsseite verbessern.', distribution: 'Hilfen konzentrieren sich auf verletzliche Gruppen.', conflict: 'Budget- und Preisrisiko versus sozialer Ausgleich.', assumptions: ['Hilfen laufen aus.', 'Angebotsprojekte wirken tatsächlich.'] },
          { id: 'restrictive', label: 'Restriktiver Kurs', description: 'Keine weiteren fiskalischen Impulse.', effect: { I: -2 }, direct: 'Gesamtnachfrage erhält keinen zusätzlichen Impuls.', delayed: 'Inflation kann sinken, Beschäftigung aber schwächer reagieren.', distribution: 'Arbeitslose und verschuldete Haushalte tragen höhere Kosten.', conflict: 'Preisstabilität versus Beschäftigung und Verteilung.', assumptions: ['Inflation reagiert hinreichend auf Nachfragedämpfung.'] },
        ],
      },
    ],
  },
]

export const missionById = (id: string) => missions.find((mission) => mission.id === id) ?? missions[0]
