import type { ActorId, Flow, Mission } from './types'

export const actors: Record<ActorId, { label: string; symbol: string; decisions: string; accounts: string; blindSpot: string }> = {
  household: { label: 'Haushalte', symbol: '⌂', decisions: 'Konsum, Sparen, Arbeitsangebot', accounts: 'Yd, C, S, T, TR', blindSpot: 'Individuelles Sparen ist nicht automatisch gesamtwirtschaftliche Nachfrage.' },
  firm: { label: 'Unternehmen', symbol: '⌘', decisions: 'Produktion, Investition, Preise, Beschäftigung', accounts: 'Umsatz, Löhne, I, Lager', blindSpot: 'Umsatz und Gewinn sind nicht identisch.' },
  state: { label: 'Staat', symbol: '⚑', decisions: 'Steuern, Transfers, Ausgaben', accounts: 'T, TR, G, Budgetsaldo', blindSpot: 'Defizit ist ein Strom; Staatsschulden sind ein Bestand.' },
  finance: { label: 'Finanzsektor', symbol: '▦', decisions: 'Kreditbedingungen und Weitergabe des Zinses', accounts: 'Kredite, Einlagen, Zins', blindSpot: 'Günstiger Kredit garantiert keine Investition.' },
  foreign: { label: 'Ausland', symbol: '◎', decisions: 'Export- und Importnachfrage', accounts: 'X, M', blindSpot: 'Importe sind eine Entnahme, aber nicht grundsätzlich negativ.' },
}

export const flows: Flow[] = [
  { id: 'labor', from: 'household', to: 'firm', label: 'Faktorleistungen', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'income' },
  { id: 'income', from: 'firm', to: 'household', label: 'Faktoreinkommen', kind: 'money', amount: 620, period: 'je Quartal', counterpart: 'labor' },
  { id: 'goods', from: 'firm', to: 'household', label: 'Konsumgüter und Dienste', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'consumption' },
  { id: 'consumption', from: 'household', to: 'firm', label: 'Konsumausgaben C', kind: 'money', amount: 500, period: 'je Quartal', counterpart: 'goods' },
  { id: 'tax', from: 'household', to: 'state', label: 'Steuern T', kind: 'tax-transfer', amount: 120, period: 'je Quartal', counterpart: 'publicServices' },
  { id: 'publicServices', from: 'state', to: 'household', label: 'Öffentliche Leistungen', kind: 'goods', amount: null, period: 'je Quartal', counterpart: 'tax' },
  { id: 'transfer', from: 'state', to: 'household', label: 'Transfers TR', kind: 'tax-transfer', amount: 32, period: 'je Quartal', counterpart: 'tax' },
  { id: 'saving', from: 'household', to: 'finance', label: 'Sparen S', kind: 'credit-interest', amount: 122, period: 'je Quartal', counterpart: 'credit' },
  { id: 'credit', from: 'finance', to: 'firm', label: 'Kredite für Investitionen', kind: 'credit-interest', amount: 110, period: 'je Quartal', counterpart: 'interest' },
  { id: 'interest', from: 'firm', to: 'finance', label: 'Zins und Tilgung', kind: 'money', amount: null, period: 'je Quartal', counterpart: 'credit' },
  { id: 'export', from: 'firm', to: 'foreign', label: 'Exporte X', kind: 'import-export', amount: 75, period: 'je Quartal', counterpart: 'exportPayment' },
  { id: 'exportPayment', from: 'foreign', to: 'firm', label: 'Exporterlöse', kind: 'money', amount: 75, period: 'je Quartal', counterpart: 'export' },
  { id: 'import', from: 'foreign', to: 'household', label: 'Importgüter M', kind: 'import-export', amount: 105, period: 'je Quartal', counterpart: 'importPayment' },
  { id: 'importPayment', from: 'household', to: 'foreign', label: 'Importzahlungen', kind: 'money', amount: 105, period: 'je Quartal', counterpart: 'import' },
]

const basicFlowTask = {
  cards: [
    { id: 'card-goods', label: 'Konsumgüter', target: 'firm-household' },
    { id: 'card-c', label: 'Konsumausgaben', target: 'household-firm' },
    { id: 'card-labor', label: 'Arbeitsleistung', target: 'household-firm' },
    { id: 'card-wage', label: 'Lohnzahlung', target: 'firm-household' },
  ],
  zones: [
    { id: 'household-firm', label: 'Haushalte → Unternehmen' },
    { id: 'firm-household', label: 'Unternehmen → Haushalte' },
  ],
}

const governmentFlowTask = {
  cards: [
    { id: 'card-tax', label: 'Steuern T', target: 'withdrawal' },
    { id: 'card-government', label: 'Staatsausgaben G', target: 'injection' },
    { id: 'card-transfer', label: 'Transfers TR', target: 'income' },
  ],
  zones: [
    { id: 'withdrawal', label: 'Entnahme im Kreislauf' },
    { id: 'injection', label: 'Zuführung im Kreislauf' },
    { id: 'income', label: 'erhöht das verfügbare Einkommen' },
  ],
}

export const missions: Mission[] = [
  {
    id: 'sparen-investieren',
    title: 'Sparen oder investieren?',
    level: 'FOS 11',
    duration: '3 Runden · ca. 18 Minuten',
    summary: 'Starte mit Strömen und einfachen Rechnungen; untersuche erst danach Lager- und Folgewirkungen.',
    actors: ['household', 'firm'],
    initialAccounts: { C: 500, I: 80, G: 0, X: 0, M: 0, T: 0, TR: 0, S: 80 },
    initialIndicators: { growth: 1.4, inflation: 2.0, employment: 94.0, interestRate: 3.5, publicDebt: 0 },
    rounds: [
      {
        title: 'Grundlage: Wer gibt was an wen?',
        situation: 'Haushalte stellen Faktorleistungen bereit und verwenden ihr Einkommen für Konsum und Sparen.',
        learningGoal: 'Haushalte, Unternehmen, Realstrom und Geldstrom sicher unterscheiden.',
        event: 'Noch kein Schock und kein Zeitsprung: Vier Karten werden nur fachlich zugeordnet.',
        instruction: 'Ordne alle vier Karten ihrer Richtung zu. Wähle danach das passende Tauschpaar.',
        tip: 'Frage bei jeder Transaktion: Wer leistet – und wer zahlt?',
        checkAfter: 'Prüfe nur Richtung und Gegenstrom. Eine Prognose oder Zeitbegründung ist noch nicht nötig.',
        demandLevel: 'Grundlage', simulationRound: false, requiresPrediction: false, requiresRationale: false, requiresReflection: false,
        assessedCriteria: ['direction', 'accounting'],
        flowTask: basicFlowTask,
        choices: [
          { id: 'pair-consumption', label: 'Konsumgüter ↔ Konsumausgaben', description: 'Unternehmen liefern Güter; Haushalte zahlen dafür.', effect: {}, direct: 'Richtig: Güter- und Geldstrom verlaufen hier entgegengesetzt.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: true },
          { id: 'pair-wage', label: 'Arbeitsleistung ↔ Konsumgüter', description: 'Beide Ströme seien direkte Gegenleistungen derselben Transaktion.', effect: {}, direct: 'Nicht passend: Zur Arbeitsleistung gehört das Faktoreinkommen als monetärer Gegenstrom.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: false },
        ],
      },
      {
        title: 'Anwendung: S und I berechnen',
        situation: 'Die Haushalte erhalten 580 Mrd. € Einkommen und konsumieren 500 Mrd. €. Die Unternehmen planen 80 Mrd. € Investitionen.',
        learningGoal: 'Sparen und Plan-Saldo mit einer einfachen Rechnung bestimmen.',
        event: 'Auch hier gibt es noch keinen Zeitsprung: Zahlen einsetzen, Ergebnis prüfen.',
        instruction: 'Berechne zuerst S = Einkommen − Konsum. Berechne danach den Plan-Saldo I − S und wähle die passende Aussage.',
        tip: 'In dieser einfachen geschlossenen Modellstufe gilt: Entnahmen = S und Zuführungen = I.',
        checkAfter: 'Kontrolliere Rechenweg, Einheit und Vorzeichen. Eine Prognose ist noch nicht verlangt.',
        demandLevel: 'Anwendung', simulationRound: false, requiresPrediction: false, requiresRationale: false, requiresReflection: false,
        assessedCriteria: ['accounting'],
        calculationTask: {
          introduction: 'Gegeben: Einkommen = 580, C = 500 und I = 80 Mrd. € je Quartal.',
          fields: [
            { id: 'saving', label: 'Sparen S', formula: 'S = 580 − 500', answer: 80, unit: 'Mrd. € je Quartal' },
            { id: 'balance', label: 'Plan-Saldo', formula: 'I − S = 80 − 80', answer: 0, unit: 'Mrd. € je Quartal' },
          ],
        },
        choices: [
          { id: 'balanced-plans', label: 'Die geplanten Ströme sind gleich groß', description: 'S = 80 und I = 80; der Plan-Saldo beträgt 0.', effect: {}, direct: 'Richtig: In dieser Modellrunde sind geplante Entnahme und Zuführung gleich groß.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: true },
          { id: 'stability-guarantee', label: 'S = I garantiert dauerhaft Vollbeschäftigung', description: 'Aus der Rechengleichheit folge automatisch eine stabile Volkswirtschaft.', effect: {}, direct: 'Nicht richtig: Eine rechnerische Gleichheit allein garantiert weder Vollbeschäftigung noch dauerhafte Stabilität.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: false },
        ],
      },
      {
        title: 'Analyse: Mehr sparen – was folgt?',
        situation: 'Die Haushalte wollen 15 Mrd. € mehr sparen und senken dafür ihren Konsum. Die Unternehmen kennen diese Entscheidung noch nicht sicher.',
        learningGoal: 'Vom veränderten Plan-Saldo über das ungeplante Lager zur möglichen Folgerunde schließen.',
        event: 'C sinkt um 15 und S steigt um 15. Du entscheidest, ob I gleichzeitig reagiert.',
        instruction: 'Wähle eine Investitionsplanung. Formuliere dann erstmals eine Prognose mit Begründung.',
        tip: 'Vergleiche zuerst S und I. Eine Produktionswirkung folgt im Modell erst nach dem Lagersignal.',
        checkAfter: 'Prüfe Saldo, Lager-Vorzeichen, Zeitbezug und mindestens eine Annahme.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'reasoning'],
        choices: [
          { id: 'investment-flat', label: 'I bleibt bei 80 Mrd. €', description: 'Die Investitionsplanung reagiert in dieser Runde noch nicht.', effect: { C: -15, S: 15 }, direct: 'S liegt nun 15 Mrd. € über I; geplante Entnahmen überwiegen.', delayed: 'Zunächst steigt das ungeplante Lager. Bei anhaltender Lücke können Produktion, Einkommen und Beschäftigung danach sinken.', distribution: 'Beschäftigte in absatzabhängigen Bereichen tragen ein höheres Anpassungsrisiko.', conflict: 'Private Vorsorge versus gesamtwirtschaftliche Nachfrage.', assumptions: ['Unternehmen halten I zunächst konstant.', 'Preise reagieren nicht sofort vollständig.'] },
          { id: 'investment-match', label: 'I steigt ebenfalls um 15 Mrd. €', description: 'Unternehmen setzen zusätzliche Investitionsprojekte um.', effect: { C: -15, S: 15, I: 15 }, direct: 'Die zusätzlichen Investitionen gleichen das zusätzliche Sparen in der Planung aus.', delayed: 'Ob Kapazität und Beschäftigung steigen, hängt trotzdem von Absatz und Umsetzung ab.', distribution: 'Investitionsgüterbranchen profitieren eher als reine Konsumgüterbranchen.', conflict: 'Kapazitätsaufbau versus Auslastungsrisiko.', assumptions: ['Projekte sind finanzierbar.', 'Unternehmen erwarten ausreichenden Absatz.'] },
        ],
      },
    ],
  },
  {
    id: 'staat-finanzsektor',
    title: 'Staat und Finanzsektor im Kreislauf',
    level: 'FOS 11/12',
    duration: '3 Runden · ca. 25 Minuten',
    summary: 'Verfolge Steuern, Transfers, Staatsausgaben, Sparen und Kredite samt Gegenbuchungen.',
    actors: ['household', 'firm', 'state', 'finance'],
    initialAccounts: { C: 470, I: 95, G: 115, X: 0, M: 0, T: 110, TR: 30, S: 120 },
    initialIndicators: { growth: 0.8, inflation: 2.2, employment: 92.5, interestRate: 4.0, publicDebt: 860 },
    rounds: [
      {
        title: 'Grundlage: T, TR und G unterscheiden',
        situation: 'Der Staat erhebt Steuern, zahlt Transfers und kauft Güter und Dienstleistungen.',
        learningGoal: 'T, TR und G kontenlogisch unterscheiden.',
        event: 'Die drei Größen werden zunächst nur ihrer Funktion im Kreislauf zugeordnet.',
        instruction: 'Ordne T, TR und G zu. Wähle danach die fachlich richtige Beschreibung.',
        tip: 'T ist Entnahme, G ist Zuführung; TR erhöht das verfügbare Einkommen Yd.',
        checkAfter: 'Prüfe Begriffe und Kontenzuordnung. Prognosen und Zeitketten kommen erst später.',
        demandLevel: 'Grundlage', simulationRound: false, requiresPrediction: false, requiresRationale: false, requiresReflection: false,
        assessedCriteria: ['accounting', 'direction'],
        flowTask: governmentFlowTask,
        choices: [
          { id: 'state-correct', label: 'T entnimmt, G führt zu, TR erhöht Yd', description: 'Die drei Größen haben im Modell unterschiedliche Kontenfunktionen.', effect: {}, direct: 'Richtig: T, G und TR dürfen nicht als derselbe staatliche Geldstrom behandelt werden.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: true },
          { id: 'state-wrong', label: 'T, G und TR sind alle Zuführungen', description: 'Jede Zahlung mit Staatsbezug erhöhe automatisch die Güternachfrage.', effect: {}, direct: 'Nicht richtig: Nur G ist unmittelbar Bestandteil der gesamtwirtschaftlichen Güternachfrage.', delayed: '', distribution: '', conflict: '', assumptions: [], correct: false },
        ],
      },
      {
        title: 'Vom Sparen zum Kredit',
        situation: 'Banken vermitteln Einlagen und Kredite, prüfen aber Bonität und Erwartungen.',
        learningGoal: 'Kreditkanal als bedingte Wirkungskette erklären.',
        event: 'Der Marktzins fällt um einen Prozentpunkt.',
        instruction: 'Entscheide, wie stark I reagiert, und nenne die nötigen Annahmen.',
        tip: 'i ↓ bedeutet nicht automatisch I ↑.',
        checkAfter: 'Prüfe Kreditweitergabe, Kreditwürdigkeit und Absatzerwartungen.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'credit-strong', label: 'Starker Kreditimpuls', description: 'I steigt um 14 Mrd. €.', effect: { I: 14, interestRate: -1 }, direct: 'Finanzierungskosten sinken und Kreditanfragen nehmen zu.', delayed: 'Investition und später Kapazität können steigen.', distribution: 'Kreditwürdige Unternehmen profitieren stärker.', conflict: 'Wachstum versus Verschuldungs- und Preisrisiken.', assumptions: ['Banken geben den Zins weiter.', 'Bonität und Nachfrageerwartungen sind ausreichend.'] },
          { id: 'credit-weak', label: 'Schwache Weitergabe', description: 'I steigt nur um 4 Mrd. €.', effect: { I: 4, interestRate: -1 }, direct: 'Der Referenzzins sinkt, Kreditkonditionen folgen nur teilweise.', delayed: 'Die Investitionswirkung bleibt begrenzt.', distribution: 'Kleine Unternehmen profitieren bei strenger Bonitätsprüfung kaum.', conflict: 'Finanzstabilität versus breiter Kreditzugang.', assumptions: ['Risikoprämien bleiben hoch.', 'Absatzerwartungen sind verhalten.'] },
        ],
      },
      {
        title: 'Budgetsaldo und Schuldenstand',
        situation: 'Das Defizit dieser Runde verändert den Schuldenbestand, ist aber nicht mit ihm identisch.',
        learningGoal: 'Strom- und Bestandsgrößen korrekt interpretieren.',
        event: 'Die Finanzierung des Programms wird ausgewertet.',
        instruction: 'Wähle einen Konsolidierungspfad und begründe den Zeitbezug.',
        tip: 'Ein Defizit wird je Zeitraum gemessen; Schulden werden zu einem Zeitpunkt gemessen.',
        checkAfter: 'Prüfe Nebenwirkungen auf Nachfrage und Verteilung.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'gradual-budget', label: 'Schrittweise konsolidieren', description: 'T steigt in der nächsten Planung moderat.', effect: { T: 5, C: -3, S: -2 }, direct: 'Das verfügbare Einkommen sinkt leicht.', delayed: 'Der Budgetsaldo verbessert sich, die Nachfrage wird etwas gedämpft.', distribution: 'Die Wirkung hängt von der konkreten Steuerbasis ab.', conflict: 'Tragfähigkeit versus kurzfristige Stabilisierung.', assumptions: ['Steueraufkommen steigt wie geplant.', 'Keine starke Ausweichreaktion.'] },
          { id: 'protect-demand', label: 'Nachfrage zunächst schützen', description: 'Keine unmittelbare Konsolidierung.', effect: {}, direct: 'Der aktuelle Impuls bleibt bestehen.', delayed: 'Der Schuldenbestand kann durch weitere Defizite steigen.', distribution: 'Beschäftigungsrisiken werden kurzfristig begrenzt.', conflict: 'Aktuelle Beschäftigung versus künftiger Finanzierungsspielraum.', assumptions: ['Finanzierung bleibt zu tragbaren Zinsen möglich.'] },
        ],
      },
    ],
  },
  {
    id: 'export-kredit',
    title: 'Exportdämpfer und Kreditimpuls',
    level: 'FOS 13',
    duration: '4 Runden · ca. 30 Minuten',
    summary: 'Reagiere auf einen Exportausfall und bewerte den bedingten Kreditkanal.',
    actors: ['household', 'firm', 'state', 'finance', 'foreign'],
    initialAccounts: { C: 500, I: 110, G: 130, X: 75, M: 105, T: 120, TR: 32, S: 125 },
    initialIndicators: { growth: -1.8, inflation: 2.8, employment: 93.6, interestRate: 3.5, publicDebt: 1040 },
    rounds: [
      {
        title: 'Exportauftrag storniert',
        situation: 'Die Auslandsnachfrage sinkt um 12 %. Ein Auftrag über 10 Mrd. € entfällt.',
        learningGoal: 'X als Zuführung und den direkten Lagerkanal erklären.',
        event: 'X −10 Mrd. €; im selben Quartal gibt es keine Gegenmaßnahme.',
        instruction: 'Beobachte die Bilanz und entscheide, wie Unternehmen zunächst reagieren.',
        tip: 'Ein Nachfrageausfall ändert nicht augenblicklich die geplante Produktion.',
        checkAfter: 'Prüfe zuerst die Lageränderung, erst danach Produktion und Beschäftigung.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'reasoning'],
        choices: [
          { id: 'wait', label: 'Eine Runde beobachten', description: 'Produktion bleibt im laufenden Quartal geplant.', effect: { X: -10 }, direct: 'Exporterlöse und Nachfrage sinken; Lager exportierender Unternehmen steigen.', delayed: 'Bei anhaltend niedrigen Aufträgen sinken Produktion und Beschäftigung.', distribution: 'Exportorientierte Regionen und Branchen sind stärker betroffen.', conflict: 'Abwarten vermeidet Überreaktion, erhöht aber Lagerkosten.', assumptions: ['Kapazitätsreserven vorhanden.', 'Keine Gegenmaßnahme im selben Quartal.'] },
          { id: 'cut-fast', label: 'Produktion sofort kürzen', description: 'C als Einkommensfolge sinkt frühzeitig.', effect: { X: -10, C: -6 }, direct: 'Produktion und Arbeitsstunden werden rasch gekürzt.', delayed: 'Niedrigere Einkommen können den Konsum zusätzlich dämpfen.', distribution: 'Beschäftigte in Exportbranchen tragen die frühe Anpassung.', conflict: 'Lagerkosten versus Beschäftigung und Einkommen.', assumptions: ['Der Exportrückgang wird als dauerhaft eingeschätzt.'] },
        ],
      },
      {
        title: 'Kreditimpuls setzen',
        situation: 'Die Zentralbank signalisiert günstigere Finanzierung. Investitionen reagieren nur bedingt.',
        learningGoal: 'Geldpolitik mit Annahmen statt Automatismus beurteilen.',
        event: 'Der Leitzins sinkt; Kreditweitergabe und Erwartungen sind offen.',
        instruction: 'Wähle ein realistisches Investitionsszenario und dokumentiere die Annahmen.',
        tip: 'Prüfe Zinsweitergabe, Bonität, Erwartungen und Kapazitätsauslastung.',
        checkAfter: 'Trenne direkten Finanzierungseffekt und verzögerte Realwirkung.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'i-medium', label: 'I steigt moderat um 8', description: 'Nur solide Projekte werden vorgezogen.', effect: { I: 8, interestRate: -0.75 }, direct: 'Kreditkosten sinken für einen Teil der Unternehmen.', delayed: 'Investitionsnachfrage stützt Produktion; Kapazität folgt später.', distribution: 'Bonitätsstarke Unternehmen profitieren früher.', conflict: 'Stabilisierung versus Verschuldung und Inflation.', assumptions: ['Banken geben den Zins teilweise weiter.', 'Unternehmen erwarten eine Nachfrageerholung.'] },
          { id: 'i-none', label: 'I reagiert kaum', description: 'Unsicherheit dominiert den Zinseffekt.', effect: { I: 1, interestRate: -0.75 }, direct: 'Finanzierung wird günstiger, aber Projekte werden nicht ausgelöst.', delayed: 'Der Exportdämpfer bleibt weitgehend bestehen.', distribution: 'Haushalte mit Zinseinkommen und Kreditnehmende sind unterschiedlich betroffen.', conflict: 'Niedrige Zinsen ohne starken Realimpuls.', assumptions: ['Absatzerwartungen bleiben schwach.', 'Kreditwürdigkeit begrenzt die Nachfrage.'] },
        ],
      },
      {
        title: 'Fiskalische Ergänzung',
        situation: 'Die Kreditwirkung reicht allein möglicherweise nicht zur Stabilisierung.',
        learningGoal: 'Fiskal- und Geldpolitik samt Zielkonflikten vergleichen.',
        event: 'Der Staat kann öffentliche Investitionen vorziehen.',
        instruction: 'Steuere G und berücksichtige Budget, Importe und Umsetzungsverzögerung.',
        tip: 'Ein Teil zusätzlicher Nachfrage kann in M abfließen.',
        checkAfter: 'Prüfe Plan-Saldo, Importanteil und Budgetwirkung.',
        demandLevel: 'Beurteilung', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'g-targeted', label: 'G +10, M +2', description: 'Gezielte Infrastruktur mit Importanteil.', effect: { G: 10, M: 2 }, direct: 'Die inländische Nachfrage steigt netto um 8 Mrd. €.', delayed: 'Beschäftigung und Produktivität können nach Vergabe steigen.', distribution: 'Begünstigt zunächst ausführende Branchen und Regionen.', conflict: 'Budgetdefizit und Importleck versus Stabilisierung.', assumptions: ['Projekte sind umsetzungsreif.', 'Es bestehen Kapazitätsreserven.'] },
          { id: 'no-g', label: 'Keine Fiskalmaßnahme', description: 'Automatische Anpassung abwarten.', effect: {}, direct: 'Der Staat setzt keinen zusätzlichen Nachfrageimpuls.', delayed: 'Private Anpassungen bestimmen Produktion und Beschäftigung.', distribution: 'Exportbranchen tragen den Schock stärker.', conflict: 'Budgetschonung versus Konjunkturstabilisierung.', assumptions: ['Private Nachfrage erholt sich ohne Staatseingriff.'] },
        ],
      },
      {
        title: 'Zielkonflikte auswerten',
        situation: 'Export, Kredit und Fiskalpolitik wirken mit verschiedenen Verzögerungen.',
        learningGoal: 'Wirkung, Annahme, Verteilung und Zielkonflikt zusammenführen.',
        event: 'Die Schlussrunde verlangt eine robuste statt eindeutige Empfehlung.',
        instruction: 'Wähle die Schwerpunktsetzung und reflektiere Unsicherheit.',
        tip: 'Mehrere fachlich vertretbare Antworten sind möglich, wenn die Bedingungen benannt sind.',
        checkAfter: 'Prüfe alle sechs Feedbackdimensionen.',
        demandLevel: 'Beurteilung', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'balanced', label: 'Befristeter Mix', description: 'Gezielte Fiskalstütze, vorsichtiger Kreditimpuls, Evaluation.', effect: { G: 4, I: 3, M: 1 }, direct: 'Zuführungen steigen stärker als Entnahmen.', delayed: 'Stabilisierung bleibt von Weitergabe und Erwartungen abhängig.', distribution: 'Gezielte Ausgestaltung kann Belastungen begrenzen.', conflict: 'Beschäftigung, Inflation und Budget müssen gemeinsam beobachtet werden.', assumptions: ['Maßnahmen sind befristet.', 'Inflationserwartungen bleiben verankert.'] },
          { id: 'stability', label: 'Preis- und Budgetstabilität', description: 'Keine weitere Nachfrageausweitung.', effect: {}, direct: 'Inflations- und Budgetrisiken werden nicht zusätzlich erhöht.', delayed: 'Erholung von Beschäftigung kann langsamer verlaufen.', distribution: 'Arbeitslose und exportabhängige Regionen tragen höhere Anpassungskosten.', conflict: 'Stabilität versus Beschäftigung.', assumptions: ['Der Schock ist vorübergehend.'] },
        ],
      },
    ],
  },
  {
    id: 'oelpreisschock',
    title: 'Ölpreisschock und Zielkonflikte',
    level: 'FOS 13',
    duration: '4 Runden · ca. 30 Minuten',
    summary: 'Unterscheide Kosten- und Nachfragekanal und steuere einen schwierigen Policy-Mix.',
    actors: ['household', 'firm', 'state', 'finance', 'foreign'],
    initialAccounts: { C: 505, I: 105, G: 125, X: 85, M: 100, T: 122, TR: 28, S: 116 },
    initialIndicators: { growth: 0.6, inflation: 3.1, employment: 94.2, interestRate: 3.75, publicDebt: 1025 },
    rounds: [
      {
        title: 'Importierter Kostenschock',
        situation: 'Energieimporte verteuern sich. Die Importrechnung steigt, Unternehmen melden höhere Kosten.',
        learningGoal: 'Angebots-/Kostenkanal und Nachfragekanal trennen.',
        event: 'M steigt um 14 Mrd. €; Inflation nimmt zunächst über Kosten zu.',
        instruction: 'Wähle eine erste Reaktion und erkläre den direkten Kanal.',
        tip: 'Höhere Inflation entsteht hier nicht zuerst aus überschießender Nachfrage.',
        checkAfter: 'Prüfe Importentnahme, Realeinkommen und Kostenüberwälzung.',
        demandLevel: 'Analyse', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'target-transfer', label: 'Gezielte Transfers', description: 'TR +10; davon C +7, S +3.', effect: { M: 14, TR: 10, C: 7, S: 3 }, direct: 'Betroffene Haushalte erhalten Einkommen, der Kostenschock bleibt aber bestehen.', delayed: 'Konsum stabilisiert sich; Nachfrage kann Preisauftrieb etwas verstärken.', distribution: 'Niedrige Einkommen werden relativ stärker entlastet.', conflict: 'Sozialer Ausgleich versus Budget und Nachfrageinflation.', assumptions: ['Transfers sind zielgenau.', '70 % werden kurzfristig konsumiert.'] },
          { id: 'wait-oil', label: 'Zunächst nicht intervenieren', description: 'Nur der Importpreisschock wird verbucht.', effect: { M: 14, C: -5 }, direct: 'Reale Kaufkraft und Konsum sinken.', delayed: 'Schwächere Nachfrage kann Beschäftigung belasten.', distribution: 'Energieintensive Haushalte und Unternehmen sind stärker betroffen.', conflict: 'Inflationsbegrenzung versus Realeinkommen und Beschäftigung.', assumptions: ['Der Ölpreisanstieg ist vorübergehend.'] },
        ],
      },
      {
        title: 'Geldpolitische Reaktion',
        situation: 'Inflation liegt über Ziel, zugleich schwächt sich die reale Aktivität ab.',
        learningGoal: 'Den Zielkonflikt der Geldpolitik beim Angebotsschock erklären.',
        event: 'Die Zinsentscheidung beeinflusst Nachfrage und Erwartungen mit Verzögerung.',
        instruction: 'Stelle die Reaktion ein und begründe den Zeithorizont.',
        tip: 'Der Leitzins senkt den Ölpreis nicht direkt.',
        checkAfter: 'Prüfe Erwartungen, Kreditkanal und Beschäftigungswirkung.',
        demandLevel: 'Beurteilung', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'rate-up', label: 'Zins +0,5 Punkte', description: 'Nachfrage und Inflationserwartungen sollen gedämpft werden.', effect: { I: -7, interestRate: 0.5 }, direct: 'Finanzierungskosten steigen.', delayed: 'I und Nachfrage sinken; Kosteninflation wird nur indirekt beeinflusst.', distribution: 'Kreditnehmende werden belastet, Sparerträge können steigen.', conflict: 'Preisstabilität versus Wachstum und Beschäftigung.', assumptions: ['Zinsänderung wird weitergegeben.', 'Erwartungen reagieren.'] },
          { id: 'rate-hold', label: 'Zins halten', description: 'Zweitrundeneffekte zunächst beobachten.', effect: {}, direct: 'Keine zusätzliche Veränderung der Finanzierungskosten.', delayed: 'Bei anhaltender Inflation können Erwartungen steigen.', distribution: 'Keine neue unmittelbare Kreditbelastung.', conflict: 'Konjunkturschutz versus Glaubwürdigkeit des Inflationsziels.', assumptions: ['Lohn-Preis-Zweitrundeneffekte bleiben begrenzt.'] },
        ],
      },
      {
        title: 'Fiskalische Feinsteuerung',
        situation: 'Breite Nachfrageprogramme könnten den Preisauftrieb erhöhen; gezielte Hilfen haben andere Verteilungswirkungen.',
        learningGoal: 'Instrumente nach Zielgenauigkeit und Nebenwirkungen beurteilen.',
        event: 'Es stehen 12 Mrd. € fiskalischer Spielraum zur Diskussion.',
        instruction: 'Wähle ein Instrument und prognostiziere Verteilung und Zielkonflikt.',
        tip: 'Entlastung, Nachfrageimpuls und Angebotswirkung sind nicht identisch.',
        checkAfter: 'Prüfe zeitliche Befristung und Begünstigte.',
        demandLevel: 'Beurteilung', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'efficiency', label: 'Effizienzinvestitionen', description: 'G +12, M +3 für Energieanlagen.', effect: { G: 12, M: 3 }, direct: 'Nachfrage und Importbedarf steigen zunächst.', delayed: 'Energieeffizienz kann Kosten und Importabhängigkeit senken.', distribution: 'Gebäudeeigentümer und beteiligte Branchen profitieren zuerst.', conflict: 'Kurzfristiger Preisdruck versus langfristige Angebotswirkung.', assumptions: ['Projekte werden umgesetzt.', 'Effizienzgewinne treten ein.'] },
          { id: 'broad-tax', label: 'Breite Steuersenkung', description: 'T −12; C +7 und S +5.', effect: { T: -12, C: 7, S: 5 }, direct: 'Yd steigt, Verwendung verteilt sich auf C und S.', delayed: 'Nachfrage steigt breit, aber wenig zielgenau.', distribution: 'Absolute Entlastung kann bei höheren Einkommen größer sein.', conflict: 'Kaufkraft versus Inflation und Budget.', assumptions: ['Haushalte konsumieren knapp 60 % der Entlastung.'] },
        ],
      },
      {
        title: 'Robuste Schlussstrategie',
        situation: 'Inflation, Beschäftigung und Verteilung reagieren unterschiedlich schnell.',
        learningGoal: 'Eine bedingte Politikempfehlung formulieren.',
        event: 'Neue Daten sind unsicher; die Mission endet nach dieser Entscheidung.',
        instruction: 'Wähle eine Strategie und reflektiere, welche Daten deine Entscheidung ändern würden.',
        tip: 'Eine robuste Empfehlung nennt Bedingungen und Revisionspunkte.',
        checkAfter: 'Prüfe Kostenkanal, Nachfragekanal, Verteilung und Zeitbezug.',
        demandLevel: 'Beurteilung', simulationRound: true, requiresPrediction: true, requiresRationale: true, requiresReflection: true,
        assessedCriteria: ['accounting', 'direction', 'time', 'assumptions', 'distribution', 'reasoning'],
        choices: [
          { id: 'targeted-mix', label: 'Gezielt entlasten und investieren', description: 'Befristete Transfers plus Angebotsinvestition.', effect: { TR: 5, G: 6, C: 3, M: 1 }, direct: 'Kaufkraft und Nachfrage werden begrenzt gestützt.', delayed: 'Investitionen können die Angebotsseite verbessern.', distribution: 'Hilfen konzentrieren sich auf verletzliche Gruppen.', conflict: 'Budget- und Preisrisiko versus sozialer Ausgleich.', assumptions: ['Hilfen laufen aus.', 'Angebotsprojekte wirken tatsächlich.'] },
          { id: 'restrictive', label: 'Restriktiver Kurs', description: 'Keine weiteren fiskalischen Impulse.', effect: { I: -2 }, direct: 'Gesamtnachfrage erhält keinen zusätzlichen Impuls.', delayed: 'Inflation kann sinken, Beschäftigung aber schwächer reagieren.', distribution: 'Arbeitslose und verschuldete Haushalte tragen höhere Kosten.', conflict: 'Preisstabilität versus Beschäftigung und Verteilung.', assumptions: ['Inflation reagiert hinreichend auf Nachfragedämpfung.'] },
        ],
      },
    ],
  },
]

export const missionById = (id: string) => missions.find((mission) => mission.id === id) ?? missions[0]
